### ISSUE TITLE
"dax_tools.exe" Run error

### ISSUE THREAD

**Issue by Frankie-Ding** [jasonlaw997/DAX-Tools#1]
![image](https://user-images.githubusercontent.com/84493444/119287664-75e5ef00-bc79-11eb-882e-2309b7520680.png)

**Comment by jasonlaw997** [comment]
How did you run the exe？via pbix？

**Comment by Frankie-Ding** [comment]
![image](https://user-images.githubusercontent.com/84493444/119425670-65497d80-bd3a-11eb-9553-6454a9860af2.png)

**Comment by jasonlaw997** [comment]
![image](https://user-images.githubusercontent.com/37357651/119430370-400d3d00-bd43-11eb-8317-ccd7d32b7450.png)

Please make sure path of dax_tools is correct

**Comment by Frankie-Ding** [comment]
![image](https://user-images.githubusercontent.com/84493444/119452859-6940c400-bd69-11eb-89a0-214ff654567f.png)
![image](https://user-images.githubusercontent.com/84493444/119451261-9f7d4400-bd67-11eb-9c03-bb912cc2cc96.png)
![image](https://user-images.githubusercontent.com/84493444/119451556-fb47cd00-bd67-11eb-9138-a73e915c8b6d.png)
Still running error

**Comment by jasonlaw997** [comment]
直接点击exe，不用pbix打开，试试

**Comment by Frankie-Ding** [comment]
![image](https://user-images.githubusercontent.com/84493444/119454392-1405b200-bd6b-11eb-803d-c9bb8df8cef2.png)

**Comment by jasonlaw997** [comment]
发布了一个新版本v1.0.2，下载试试

**Comment by Frankie-Ding** [comment]
![image](https://user-images.githubusercontent.com/84493444/119458172-fcf39f80-bd2b-11eb-904d-3f5050f52d82.png)
![image](https://user-images.githubusercontent.com/84493444/119458268-1563ba00-bd2c-11eb-9acc-818b8ff1253c.png)

**Comment by jasonlaw997** [comment]
右键管理员打开试试？我在别的电脑打开是完全没问题的

**Comment by Frankie-Ding** [comment]
The same goes for running as administrator

**Comment by Frankie-Ding** [comment]
I changed a computer is the same

**Comment by Frankie-Ding** [comment]
鼠标右键以管理员身份运行也不行，换了一台电脑也是一样。可能我的电脑少装了什么软件。
